name: Workflow Manual
on:
  workflow_dispatch:
    inputs:
      nombre_apellidos:
        description: 'Tu nombre y Apellidos'
        required: true
        default: 'Nombre Apellidos'

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo personalizado
        run: echo "${{ github.event.inputs.nombre_apellidos }}

